# Generated by Django 3.0.6 on 2020-05-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckService',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('accountno', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('service_id', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'check_service',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.FloatField(blank=True, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('customername', models.CharField(blank=True, max_length=50, null=True)),
                ('otchestvo', models.CharField(blank=True, max_length=50, null=True)),
                ('accountno', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.FloatField(blank=True, null=True)),
                ('creditsum', models.BigIntegerField(blank=True, null=True)),
                ('creditpurpose', models.CharField(blank=True, max_length=20, null=True)),
                ('companyname', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='PayService',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('accountno', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('service_id', models.FloatField(blank=True, null=True)),
                ('pay_id', models.FloatField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('sum', models.FloatField(blank=True, null=True)),
                ('status', models.FloatField(blank=True, null=True)),
                ('position', models.BigIntegerField(blank=True, null=True)),
                ('positionn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pay_service',
            },
        ),
    ]
